//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAppWithLogin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class empdata
    {
        public int id { get; set; }
        public string ename { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> salay { get; set; }
        public string city { get; set; }
    }
}
